### ISSUE TITLE
Doesn't load.

### ISSUE THREAD

**Issue by gbougakov** [Railcraft/Railcraft#1061]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/6/17 12:57 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:225)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at mods.railcraft.client.render.models.resource.OutfittedTrackItemModel.bake(OutfittedTrackItemModel.java:70)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:225)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at mods.railcraft.client.render.models.resource.OutfittedTrackItemModel.bake(OutfittedTrackItemModel.java:70)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 44442352 bytes (42 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJA	GunMod{1.0.0} [GunMod] (gunmod.jar) 
	UCHIJA	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
	UCHIJA	malisisdoors{1.10.2-5.1.5} [MalisisDoors] (malisisdoors-1.10.2-5.1.5.jar) 
	UCHIJA	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCHIJA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJA	Signals{1.0} [Signals] (Signals-1.10.2-0.5.0-universal.jar) 
	UCHIJA	trafficstuffmod{3.0.0} [Traffic Stuff Mod] (Traffic Stuff Mod [3.0.0].jar) 
	UCHIJA	worldedit{6.1.6} [WorldEdit] (worldedit.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4534' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz

**Comment by AEnterprise** [comment]
minecraft ran out of memory, you'll want to allocate more to it, 2-3GB should be enough with your set of mods
