### ISSUE TITLE
Getting crash when using in Intellij

### ISSUE THREAD

**Issue by Raycoms** [Railcraft/Railcraft#1086]
I'm currently getting crashes when I try to use railcraft in intellij:

minecraft_version=1.10.2
forge_version=12.18.2.2107

[11:16:02] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1174) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1139) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.AbstractMethodError: mods.railcraft.common.blocks.tracks.outfitted.ItemTrackOutfitted$$Lambda$297/744476363.getModelLocation(Lnet/minecraft/item/ItemStack;)Lnet/minecraft/client/renderer/block/model/ModelResourceLocation;
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:52) ~[ItemModelMesher.class:?]
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:253) ~[RenderItem.class:?]
	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:356) ~[RenderItem.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:298) ~[GuiContainer.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:114) ~[GuiContainer.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:59) ~[InventoryEffectRenderer.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:634) ~[GuiContainerCreative.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1147) ~[EntityRenderer.class:?]
	... 15 more
[11:16:02] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:649]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/27/17 11:16 AM
Description: Rendering item

java.lang.AbstractMethodError: mods.railcraft.common.blocks.tracks.outfitted.ItemTrackOutfitted$$Lambda$297/744476363.getModelLocation(Lnet/minecraft/item/ItemStack;)Lnet/minecraft/client/renderer/block/model/ModelResourceLocation;
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:253)
	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:356)
	at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:298)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:114)
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:59)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:634)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1147)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1139)
	at net.minecraft.client.Minecraft.run(Minecraft.java:406)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:253)

-- Item being rendered --
Details:
	Item Type: mods.railcraft.common.blocks.tracks.outfitted.ItemTrackOutfitted@4a3ebba6
	Item Aux: 0
	Item NBT: {railcraft:{rail:"railcraft_high_speed_electric",kit:"railcraft_priming"}}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:356)
	at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:298)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:114)
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:59)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:634)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (282, 53). Absolute: (565, 372)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

**Comment by Raycoms** [comment]
Ah should've used the dev jar. 
Closed
