### ISSUE TITLE
Forge Crashes on startup

### ISSUE THREAD

**Issue by Xxepic-gamerxX** [Railcraft/Railcraft#1201]
I am playing with many mods and it appears that MC crashes with what im guessing incompatabily issues with another mod in 1.7.10.I attach my crash log here (pastebin didn't seem to work at all)
[crash-2017-05-12_20.49.10-client.txt](https://github.com/CovertJaguar/Railcraft/files/998273/crash-2017-05-12_20.49.10-client.txt)

**Comment by bookerthegeek** [comment]
I have no idea why you posted that here. The first lines of the crash are
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.potion.Potion.<init>(Potion.java:68)
	at blusunrize.immersiveengineering.common.util.IEPotions$IEPotion.<init>(IEPotions.java:92)
	at blusunrize.immersiveengineering.common.util.IEPotions.init(IEPotions.java:32)
	at blusunrize.immersiveengineering.common.IEContent.init(IEContent.java:508)
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:99)
```
Go post this at the correct repository please, but do not expect much help as ```Minecraft Version: 1.7.10``` is now E.O.L. for Immersive Engineering and most other mods.

**Comment by liach** [comment]
@Xxepic-gamerxX Go to https://github.com/Blusunrize/ImmersiveEngineering/issues/new

**Comment by Xxepic-gamerxX** [comment]
well thx...yea i dont understand much code...i only posted here as the report said the railcraft errored but thanks anyways
