### ISSUE TITLE
java.lang.RuntimeException: Invalid Fingerprint

### ISSUE THREAD

**Issue by wwng2333** [Railcraft/Railcraft#1213]
I rebuild the mod with jdk1.8
```bash
wwng@DESKTOP-1OTCGLE MINGW64 /f/MC_dev/Railcraft (mc-1.10.2)
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

build log:
```bash
wwng@DESKTOP-1OTCGLE MINGW64 /f/MC_dev/Railcraft (mc-1.10.2)
$ ./gradlew build
#################################################
         ForgeGradle 2.2-SNAPSHOT-eb2e450
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:apiZip UP-TO-DATE
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava UP-TO-DATE
:compileApiJava
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:processApiResources UP-TO-DATE
:apiClasses
:sourceMainJava UP-TO-DATE
:compileJava
F:\MC_dev\Railcraft\build\sources\main\java\mods\railcraft\common\plugins\forge\DataManagerPlugin.java:106: 警告: Reflection是内部专用 API, 可能会在未来发行版中删除
        Class<?> clazz = sun.reflect.Reflection.getCallerClass(2);
                                    ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个警告
:processResources UP-TO-DATE
:classes
:devJar
:jar
:sourceTestJava UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:getVersionJson
:extractUserdev UP-TO-DATE
:genSrgs SKIPPED
:reobfJar
:assemble
:check UP-TO-DATE
:signDevJar SKIPPED
:signMainJar SKIPPED
:build

BUILD SUCCESSFUL

Total time: 20.067 secs
```
and i throw it to mod folder, run the game, game crashed.
here is the log:
```bash
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 17-5-17 下午7:58
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: java.lang.RuntimeException: Invalid Fingerprint
	at mods.railcraft.common.core.Railcraft.fingerprintError(Railcraft.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 119861568 bytes (114 MB) / 321912832 bytes (307 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	UC	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	UE	railcraft{10.2.0-alpha-1-unofficial} [Railcraft] (Railcraft_1.10.2-10.2.0-alpha-1-unofficial.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.89' Renderer: 'GeForce GTX 960/PCIe/SSE2'
```

I have no idea about this, plz help. :((

**Comment by wwng2333** [comment]
binary file: 
https://transfer.sh/OEFAC/Railcraft_1.10.2-10.2.0-alpha-1-unofficial.jar
https://transfer.sh/hqRw6/Railcraft_1.10.2-10.2.0-alpha-1-unofficial-dev.jar

**Comment by wwng2333** [comment]
My forge version:
1.10.2-forge1.10.2-12.18.3.2281

**Comment by BrisingrAerowing** [comment]
The official Jar is signed and errors out if the signing doesn't happen, which it doesn't in an unofficial build. You need to comment out [this method](https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/core/Railcraft.java#L155) to prevent the crash. Also comment out the attribute right above it to prevent other errors.

**Comment by CovertJaguar** [comment]
Unofficial builds are unsupported.

**Comment by liach** [comment]
However, you can play Railcraft in your own workspace. Run `./gradlew sCiW runClient` to play.
你可以用命令行指令玩，只要输上面那个就行了。
