### ISSUE TITLE
Infinite Loop in Tunnel Bore Ballast Code

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#1296]
The recently accepted PR #1280 for ballast introduced an infinite loop into the code.

```
"Server thread" #17 prio=5
RUNNABLE
	at net.minecraft.world.chunk.Chunk.func_177435_g(Chunk.java:465)
	at net.minecraft.world.World.func_180495_p(World.java:843)
	at net.minecraft.world.World.func_175623_d(World.java:223)
	at mods.railcraft.common.plugins.forge.WorldPlugin.isBlockAir(WorldPlugin.java:80)
	at mods.railcraft.common.carts.EntityTunnelBore.placeBallast(EntityTunnelBore.java:682)
	at mods.railcraft.common.carts.EntityTunnelBore.func_70071_h_(EntityTunnelBore.java:427)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by liach** [comment]
This is actually a one-line fix.

**Comment by liach** [comment]
@CovertJaguar Can I just add some sort of phase manager for bores?
