### ISSUE TITLE
[1.12.2] Minecraft crashes after moving a while

### ISSUE THREAD

**Issue by lion0738** [Railcraft/Railcraft#1455]
https://pastebin.com/SEaFKsdi
https://pastebin.com/EMw0b8xt

Tested by using 'gradlew runclient' command.
Minecraft throws this error randomly when moving around.

java.lang.ArithmeticException: / by zero
    at net.minecraft.entity.EntityTrackerEntry.updatePlayerList(EntityTrackerEntry.java:191)
    at net.minecraft.entity.EntityTracker.tick(EntityTracker.java:297)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:854)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
    at java.lang.Thread.run(Thread.java:748)

I also tried running only with railcraft and most recent forge, same crash happened.
only removing railcraft solved this problem.

**Comment by liach** [comment]
It is caused by the incorrect update frequency of zero. I will find out which minecart exactly caused this issue.

**Comment by liach** [comment]
@lion0738 Can you test if this issue still happens in the latest commit of indev-1.12.2?

**Comment by lion0738** [comment]
It's working without crash now.

**Comment by liach** [comment]
Thanks!

**Comment by liach** [comment]
Thanks for the report! Feel free to open more issues if you find more like this one.
