### ISSUE TITLE
Router switch crashes client

### ISSUE THREAD

**Issue by Kiritow** [Railcraft/Railcraft#1546]
**Description of the Bug**
When the router switch switches, the client gets freezed and then gets crashed in a few seconds. Tested in both singleplayer and multiplayer (The server won't crash) .

**To Reproduce**
1. Place some tracks on the ground. (reinforced track)
2. Place one locomotive, two tank minecarts and one chunkloader minecart. Then connect them.
3. Use spike to fork a rail. Then place a router switch next to it.
4. Grab a route table and write `Dest=A` in it. Grab a golden ticket and write `Dest=A` on it.
5. Place the route table in the router switch. Place the golden ticket in the locomotive.
6. Start the train. When it reaches the router, the client crashes.

**Environment**
 - Version Railcraft 12.0.0-alpha-6
 - Forge version 2775

**Additional context**
the crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/26/18 7:24 PM
Description: Ticking block entity

java.lang.RuntimeException: Don't access trains on the client! It won't work!
	at mods.railcraft.common.carts.TrainManager.forWorld(TrainManager.java:41)
	at mods.railcraft.common.carts.Train.getManager(Train.java:67)
	at mods.railcraft.common.carts.Train.getTrain(Train.java:71)
	at mods.railcraft.common.util.routing.RoutingLogic.getRoutableCart(RoutingLogic.java:88)
	at mods.railcraft.common.util.routing.RoutingLogic.evaluate(RoutingLogic.java:110)
	at mods.railcraft.common.util.routing.RoutingLogic.matches(RoutingLogic.java:104)
	at mods.railcraft.common.blocks.machine.wayobjects.actuators.TileActuatorRouting.lambda$shouldSwitch$0(TileActuatorRouting.java:186)
	at java.util.Optional.map(Unknown Source)
	at mods.railcraft.common.blocks.machine.wayobjects.actuators.TileActuatorRouting.shouldSwitch(TileActuatorRouting.java:186)
	at mods.railcraft.common.blocks.tracks.outfitted.kits.TrackKitSwitch.update(TrackKitSwitch.java:317)
	at mods.railcraft.common.blocks.tracks.outfitted.TileTrackOutfittedTicking.func_73660_a(TileTrackOutfittedTicking.java:23)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mods.railcraft.common.carts.TrainManager.forWorld(TrainManager.java:41)
	at mods.railcraft.common.carts.Train.getManager(Train.java:67)
	at mods.railcraft.common.carts.Train.getTrain(Train.java:71)
	at mods.railcraft.common.util.routing.RoutingLogic.getRoutableCart(RoutingLogic.java:88)
	at mods.railcraft.common.util.routing.RoutingLogic.evaluate(RoutingLogic.java:110)
	at mods.railcraft.common.util.routing.RoutingLogic.matches(RoutingLogic.java:104)
	at mods.railcraft.common.blocks.machine.wayobjects.actuators.TileActuatorRouting.lambda$shouldSwitch$0(TileActuatorRouting.java:186)
	at java.util.Optional.map(Unknown Source)
	at mods.railcraft.common.blocks.machine.wayobjects.actuators.TileActuatorRouting.shouldSwitch(TileActuatorRouting.java:186)
	at mods.railcraft.common.blocks.tracks.outfitted.kits.TrackKitSwitch.update(TrackKitSwitch.java:317)
	at mods.railcraft.common.blocks.tracks.outfitted.TileTrackOutfittedTicking.func_73660_a(TileTrackOutfittedTicking.java:23)

-- Block entity being ticked --
Details:
	Name: railcraft:track.outfitted.ticking // mods.railcraft.common.blocks.tracks.outfitted.TileTrackOutfittedTicking
	Block type: ID #381 (tile.railcraft.track.outfitted // mods.railcraft.common.blocks.tracks.outfitted.BlockTrackOutfitted // railcraft:track_outfitted)
	Block data value: 9 / 0x9 / 0b1001
	Block location: World: (111,4,-432), Chunk: (at 15,0,0 in 6,-27; contains blocks 96,0,-432 to 111,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #381 (tile.railcraft.track.outfitted // mods.railcraft.common.blocks.tracks.outfitted.BlockTrackOutfitted // railcraft:track_outfitted)
	Actual block data value: 9 / 0x9 / 0b1001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kirito'/29, l='MpServer', x=108.47, y=4.00, z=-434.19]]
	Chunk stats: MultiplayerChunkCache: 506, 506
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (114,4,-436), Chunk: (at 2,0,12 in 7,-28; contains blocks 112,0,-448 to 127,255,-433), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1874 game time, 1874 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 73 total; [EntitySlime['史莱姆'/313222, l='MpServer', x=169.46, y=4.75, z=-488.56], EntitySlime['史莱姆'/203790, l='MpServer', x=131.99, y=4.00, z=-478.65], EntitySlime['史莱姆'/215310, l='MpServer', x=172.24, y=4.03, z=-362.02], EntityCow['牛'/79247, l='MpServer', x=130.39, y=4.00, z=-506.43], EntitySheep['羊'/79249, l='MpServer', x=128.29, y=4.00, z=-505.37], EntitySlime['史莱姆'/347669, l='MpServer', x=56.07, y=5.04, z=-484.66], EntityCow['牛'/79248, l='MpServer', x=131.44, y=4.00, z=-505.85], EntitySheep['羊'/79250, l='MpServer', x=127.50, y=4.00, z=-506.50], EntitySlime['史莱姆'/138385, l='MpServer', x=55.85, y=4.00, z=-409.91], EntitySlime['史莱姆'/273808, l='MpServer', x=136.80, y=5.18, z=-478.66], EntityPlayerSP['Kirito'/29, l='MpServer', x=108.47, y=4.00, z=-434.19], EntitySlime['史莱姆'/191895, l='MpServer', x=140.05, y=5.17, z=-501.88], EntitySlime['史莱姆'/264465, l='MpServer', x=121.20, y=4.00, z=-399.13], EntitySlime['史莱姆'/308114, l='MpServer', x=175.71, y=4.63, z=-358.67], EntitySlime['史莱姆'/133531, l='MpServer', x=141.43, y=4.00, z=-375.01], EntitySheep['羊'/79259, l='MpServer', x=151.50, y=4.00, z=-477.50], EntitySlime['史莱姆'/16796, l='MpServer', x=128.70, y=4.00, z=-495.30], EntityHorse['马'/79261, l='MpServer', x=152.50, y=4.00, z=-472.50], EntitySheep['羊'/79260, l='MpServer', x=154.50, y=4.00, z=-482.50], EntityLocomotiveCreative['永动机车'/281370, l='MpServer', x=109.63, y=4.06, z=-431.50], EntitySlime['史莱姆'/360219, l='MpServer', x=94.65, y=4.00, z=-358.73], EntityHorse['马'/79262, l='MpServer', x=156.86, y=4.00, z=-465.99], EntityChicken['鸡'/79264, l='MpServer', x=152.50, y=4.00, z=-477.50], EntitySlime['史莱姆'/55074, l='MpServer', x=139.14, y=4.00, z=-487.91], EntitySlime['史莱姆'/135073, l='MpServer', x=67.60, y=4.00, z=-433.60], EntitySheep['羊'/79271, l='MpServer', x=93.19, y=4.00, z=-419.40], EntityHorse['马'/79273, l='MpServer', x=95.84, y=4.00, z=-411.80], EntitySlime['史莱姆'/252970, l='MpServer', x=122.88, y=4.14, z=-400.65], EntityHorse['马'/79274, l='MpServer', x=109.93, y=4.00, z=-418.90], EntityHorse['马'/79277, l='MpServer', x=104.15, y=4.00, z=-424.82], EntityPig['猪'/79279, l='MpServer', x=92.78, y=4.00, z=-422.34], EntityHorse['马'/79278, l='MpServer', x=75.88, y=4.00, z=-419.65], EntitySheep['羊'/79281, l='MpServer', x=172.99, y=4.00, z=-464.74], EntitySheep['羊'/79280, l='MpServer', x=167.79, y=4.00, z=-459.68], EntitySheep['羊'/79283, l='MpServer', x=180.50, y=4.00, z=-464.50], EntitySheep['羊'/79282, l='MpServer', x=174.63, y=4.00, z=-472.21], EntityPig['猪'/79285, l='MpServer', x=95.50, y=4.00, z=-378.50], EntitySlime['史莱姆'/370609, l='MpServer', x=144.57, y=4.00, z=-379.46], EntityPig['猪'/79284, l='MpServer', x=97.50, y=4.00, z=-383.50], EntityPig['猪'/79286, l='MpServer', x=95.50, y=4.00, z=-379.50], EntitySlime['史莱姆'/299187, l='MpServer', x=137.53, y=4.00, z=-492.29], EntityCartWorldspikeStandard['标准界钉车'/330162, l='MpServer', x=105.13, y=4.06, z=-431.50], EntitySlime['史莱姆'/264508, l='MpServer', x=183.18, y=4.96, z=-490.80], EntityDonkey['驴'/79288, l='MpServer', x=105.21, y=4.00, z=-390.08], EntityChicken['鸡'/79291, l='MpServer', x=106.09, y=4.00, z=-387.20], EntityDonkey['驴'/79290, l='MpServer', x=106.20, y=4.00, z=-391.27], EntityChicken['鸡'/79297, l='MpServer', x=150.50, y=4.00, z=-511.50], EntityCartTank['蓄水槽车'/320581, l='MpServer', x=106.67, y=4.06, z=-431.50], EntitySlime['史莱姆'/46658, l='MpServer', x=133.41, y=4.00, z=-481.76], EntityChicken['鸡'/79298, l='MpServer', x=148.50, y=4.00, z=-510.50], EntityCow['牛'/79301, l='MpServer', x=83.88, y=4.00, z=-433.15], EntitySlime['史莱姆'/142022, l='MpServer', x=148.51, y=4.80, z=-459.86], EntitySlime['史莱姆'/269376, l='MpServer', x=32.47, y=5.06, z=-404.90], EntityChicken['鸡'/79300, l='MpServer', x=152.50, y=4.00, z=-511.50], EntityCow['牛'/79303, l='MpServer', x=79.58, y=4.00, z=-410.84], EntityCow['牛'/79302, l='MpServer', x=99.18, y=4.00, z=-399.72], EntitySlime['史莱姆'/277315, l='MpServer', x=144.26, y=4.03, z=-386.67], EntityPig['猪'/79305, l='MpServer', x=103.50, y=4.00, z=-420.06], EntityCartTank['蓄水槽车'/285514, l='MpServer', x=108.09, y=4.06, z=-431.50], EntitySlime['史莱姆'/279627, l='MpServer', x=169.99, y=4.80, z=-377.62], EntityChicken['鸡'/79310, l='MpServer', x=187.50, y=4.00, z=-421.50], EntitySlime['史莱姆'/275038, l='MpServer', x=166.74, y=4.00, z=-467.50], EntitySlime['史莱姆'/17888, l='MpServer', x=146.76, y=4.00, z=-445.86], EntitySlime['史莱姆'/84961, l='MpServer', x=116.00, y=4.00, z=-504.69], EntitySlime['史莱姆'/102497, l='MpServer', x=111.06, y=4.42, z=-478.91], EntitySlime['史莱姆'/143584, l='MpServer', x=55.09, y=5.00, z=-493.39], EntitySlime['史莱姆'/84962, l='MpServer', x=133.37, y=5.17, z=-493.33], EntitySlime['史莱姆'/295136, l='MpServer', x=184.07, y=5.00, z=-482.91], EntitySlime['史莱姆'/370292, l='MpServer', x=136.56, y=5.17, z=-482.85], EntitySlime['史莱姆'/256757, l='MpServer', x=136.01, y=4.00, z=-379.27], EntitySlime['史莱姆'/377715, l='MpServer', x=132.50, y=4.00, z=-481.50], EntitySlime['史莱姆'/94712, l='MpServer', x=79.17, y=4.00, z=-358.13], EntitySlime['史莱姆'/248056, l='MpServer', x=72.14, y=5.25, z=-488.61]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1130691376 bytes (1078 MB) / 2518532096 bytes (2401 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 4 total; -Xmx4096m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                  | Source                                   | Signature                                |
	|:--------- |:------------------- |:------------------------ |:---------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                   | minecraft.jar                            | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                     | minecraft.jar                            | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2775.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.5.2775             | forge-1.12.2-14.23.5.2775.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | opencomputers|core  | 1.7.3.146                | minecraft.jar                            | None                                     |
	| UCHIJAAAA | appliedenergistics2 | rv6-stable-3             | appliedenergistics2-rv6-stable-3.jar     | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAA | buildcraftlib       | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftcore      | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftbuilders  | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftenergy    | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftfactory   | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftrobotics  | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcrafttransport | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftsilicon   | 7.99.18                  | buildcraft-7.99.18.jar                   | None                                     |
	| UCHIJAAAA | buildcraftcompat    | 7.99.15                  | buildcraft-compat-7.99.15.jar            | None                                     |
	| UCHIJAAAA | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                 | None                                     |
	| UCHIJAAAA | asielib             | 1.0.0                    | Computronics-1.12.1-1.6.5.jar            | None                                     |
	| UCHIJAAAA | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar              | None                                     |
	| UCHIJAAAA | opencomputers       | 1.7.3.146                | OpenComputers-MC1.12.2-1.7.3.146.jar     | None                                     |
	| UCHIJAAAA | ic2                 | 2.8.104-ex112            | industrialcraft-2-2.8.104-ex112.jar      | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | railcraft           | 12.0.0-alpha-6           | railcraft-12.0.0-alpha-6.jar    | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| UCHIJAAAA | jei                 | 4.13.1.222               | jei_1.12.2-4.13.1.222.jar                | None                                     |
	| UCHIJAAAA | mekanism            | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar           | None                                     |
	| UCHIJAAAA | computronics        | 1.6.5                    | Computronics-1.12.1-1.6.5.jar            | None                                     |
	| UCHIJAAAA | flour               | 1.0.0                    | flour-1.0.0.jar                          | None                                     |
	| UCHIJAAAA | cfm                 | 5.17.0                   | furniture-5.17.0-1.12.2.jar              | None                                     |
	| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks       | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar        | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar              | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                 | None                                     |
	| UCHIJAAAA | mekanismgenerators  | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar | None                                     |
	| UCHIJAAAA | mousetweaks         | 2.9                      | MouseTweaks-2.9-mc1.12.2.jar             | None                                     |
	| UCHIJAAAA | storagedrawers      | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar          | None                                     |
	| UCHIJAAAA | tconstruct          | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar          | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 5500'
	AE2 Version: stable rv6-stable-3 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2775
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: OC濠电偞鍨堕幖鈺呭储娴犲鍑犻柛鎰典悍閹峰嘲鈽夊▎妯荤暥缂備降鍔戞禍璺侯嚕閸洖绠涙い鏍ㄦ皑閻涒晠姊洪崨濠勫闁瑰嚖鎷�(闂備浇顕栭崜姘辨崲閸愵亣濮虫い鏃�鎷濋幏鐑芥偡闁箑鍓紓鍌氱▌閹凤拷).zip (incompatible)
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
```

**Comment by liach** [comment]
感谢你又找到一处代码漏洞！我们会尽快修复。
Thank you for finding another misuse of train code! We will fix it as soon as possible.

**Comment by liach** [comment]
Fixed in alpha 7.
