### ISSUE TITLE
Tank cart gui not opening

### ISSUE THREAD

**Issue by baysupercool** [Railcraft/Railcraft#1608]
**Description of the Bug**
Tank cart's gui doesn't open when I click on it.

**To Reproduce**
1. Place tank cart
2. Click on it
3. Nothing happens

**Expected behavior**
Tank cart gui should open

**Logs & Environment**
forge1.12.2-14.23.5.2796
railcraft-12.0.0-beta-2

**Comment by liach** [comment]
It might be caused by lag. Are you sure you waited after you clicked? If this is your first click, you will have a few seconds which you will feel that nothing is going on, but suddenly you cannot move any more and the gui should appear. For further clicks, gui appears faster.

**Comment by baysupercool** [comment]
It's not related to lag.
When I looked to the log I saw this:

(I couldn't post this on pastebin, it's banned here for some reason.)

` [Server thread/WARN] [railcraft]: Error when attempting to build gui container TANK: java.lang.ClassCastException: mods.railcraft.common.carts.EntityCartTank cannot be cast to mods.railcraft.common.blocks.machine.ITankTile
java.lang.ClassCastException: mods.railcraft.common.carts.EntityCartTank cannot be cast to mods.railcraft.common.blocks.machine.ITankTile
	at mods.railcraft.common.gui.containers.FactoryContainer.build(FactoryContainer.java:89) [FactoryContainer.class:?]
	at mods.railcraft.common.gui.GuiHandler.getServerGuiElement(GuiHandler.java:59) [GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) [NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) [FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) [aed.class:?]
	at mods.railcraft.common.gui.GuiHandler.openGui(GuiHandler.java:44) [GuiHandler.class:?]
	at mods.railcraft.common.carts.CartBaseContainer.openRailcraftGui(CartBaseContainer.java:218) [CartBaseContainer.class:?]
	at mods.railcraft.common.carts.CartBaseContainer.doInteract(CartBaseContainer.java:100) [CartBaseContainer.class:?]
	at mods.railcraft.common.carts.EntityCartTank.doInteract(EntityCartTank.java:157) [EntityCartTank.class:?]
	at mods.railcraft.common.carts.CartBaseContainer.func_184230_a(CartBaseContainer.java:94) [CartBaseContainer.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) [aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1073) [pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
`

**Comment by CovertJaguar** [comment]
Oh....hmm. That would be my fault.
