### ISSUE TITLE
[1.12.2][Beta 4] ConcurrentModificationException

### ISSUE THREAD

**Issue by gudenau** [Railcraft/Railcraft#1675]
**Description of the Bug**

When loading the world with RailCraft installed, removing it allowed the world to load.

**To Reproduce**

(This is according to the player)
1. Break down a boiler
2. Rebuild the boiler
3. World dies

**Expected behavior**

Server not dieing.

**Screenshots & Video**

**Logs & Environment**

 - Full log: 
[latest.log](https://github.com/Railcraft/Railcraft/files/2793742/latest.log)

 - Crash report (If available): 

**Additional context**

Mod dir list:
```
drwxr-xr-x 2 minecraft minecraft     4096 Jan 14 14:45 1.12.2
-rw-r--r-- 1 minecraft minecraft   165113 Jan 14 14:45 AE2WTLib-1.12.2-1.0.6.jar
-rw-r--r-- 1 minecraft minecraft  4062132 Jan 14 14:45 appliedenergistics2-rv6-stable-6.jar
-rw-r--r-- 1 minecraft minecraft   101437 Jan 14 14:45 AutoRegLib-1.3-24.jar
-rw-r--r-- 1 minecraft minecraft    11034 Jan 14 14:45 badwithernocookiereloaded-1.12.2-3.3.16.jar
-rw-r--r-- 1 minecraft minecraft   108450 Jan 14 14:45 Baubles-1.12-1.5.2.jar
-rw-r--r-- 1 minecraft minecraft  5122856 Jan 14 14:45 BiblioCraft[v2.4.5][MC1.12.2].jar
-rw-r--r-- 1 minecraft minecraft  4691799 Jan 14 14:45 BiomesOPlenty-1.12.2-7.0.1.2424-universal.jar
-rw-r--r-- 1 minecraft minecraft  7064754 Jan 14 14:45 BloodMagic-1.12.2-2.3.3-101.jar
-rw-r--r-- 1 minecraft minecraft   243495 Jan 14 14:45 Bookshelf-1.12.2-2.3.570.jar
-rw-r--r-- 1 minecraft minecraft 13789999 Jan 14 14:45 Botania+r1.10-358.jar
-rw-r--r-- 1 minecraft minecraft   896667 Jan 14 14:45 BrandonsCore-1.12.2-2.4.9.195-universal.jar
-rw-r--r-- 1 minecraft minecraft    96859 Jan 14 14:45 Chameleon-1.12-4.1.3.jar
-rw-r--r-- 1 minecraft minecraft   134368 Jan 14 14:45 ChickenChunks-1.12.2-2.4.1.73-universal.jar
-rw-r--r-- 1 minecraft minecraft  4310011 Jan 14 14:45 Chisel-MC1.12.2-0.2.1.35.jar
-rw-r--r-- 1 minecraft minecraft   730497 Jan 14 14:45 chiselsandbits-14.29.jar
-rw-r--r-- 1 minecraft minecraft   700785 Jan 14 14:45 CodeChickenLib-1.12.2-3.2.2.353-universal.jar
-rw-r--r-- 1 minecraft minecraft   844143 Jan 14 14:45 CoFHCore-1.12.2-4.6.1.22-universal.jar
-rw-r--r-- 1 minecraft minecraft   531831 Jan 14 14:45 CoFHWorld-1.12.2-1.3.0.6-universal.jar
-rw-r--r-- 1 minecraft minecraft   419190 Jan 14 14:45 DarkUtils-1.12.2-1.8.222.jar
-rw-r--r-- 1 minecraft minecraft     5222 Jan 14 14:45 diethopper-1.1.jar
-rw-r--r-- 1 minecraft minecraft  5674864 Jan 14 14:45 Draconic-Evolution-1.12.2-2.3.18.329-universal.jar
-rw-r--r-- 1 minecraft minecraft  2803188 Jan 14 14:45 Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar
-rw-r--r-- 1 minecraft minecraft   619577 Jan 14 14:45 EnderCore-1.12.2-0.5.44.jar
-rw-r--r-- 1 minecraft minecraft  7106613 Jan 14 14:45 EnderIO-1.12.2-5.0.39.jar
-rw-r--r-- 1 minecraft minecraft   223227 Jan 14 14:45 EnderStorage-1.12.2-2.4.5.135-universal.jar
-rw-r--r-- 1 minecraft minecraft  1001846 Jan 14 14:45 environmentaltech-1.12.2-2.0.19.1.jar
-rw-r--r-- 1 minecraft minecraft  2563518 Jan 14 14:45 ExtraCells-1.12.2-2.6.2a.jar
-rw-r--r-- 1 minecraft minecraft  3226384 Jan 14 14:45 extrautils2-1.12-1.9.8.jar
-rw-r--r-- 1 minecraft minecraft  1085265 Jan 14 14:45 ExtremeReactors-1.12.2-0.4.5.50.jar
-rw-r--r-- 1 minecraft minecraft    25347 Jan 14 14:45 FastWorkbench-1.12.2-1.6.0.jar
-rw-r--r-- 1 minecraft minecraft   136082 Jan 14 14:45 flatcoloredblocks-mc1.12-6.6.jar
-rw-r--r-- 1 minecraft minecraft   216000 Jan 14 14:45 foamfix-0.10.3-1.12.2.jar
-rw-r--r-- 1 minecraft minecraft   887644 Jan 14 14:45 forge-1.12.2-14.23.4.2736-installer.jar
-rw-r--r-- 1 minecraft minecraft  1304717 Jan 14 14:45 ForgeMultipart-1.12.2-2.6.0.79-universal.jar
-rw-r--r-- 1 minecraft minecraft   430911 Jan 14 14:45 FTBUtilities-5.3.0.71.jar
-rw-r--r-- 1 minecraft minecraft   265118 Jan 14 14:45 funky-locomotion-1.12.2-1.1.2.jar
-rw-r--r-- 1 minecraft minecraft   169528 Jan 14 14:45 Guide-API-1.12-2.1.8-63.jar
drwxr-xr-x 9 minecraft minecraft     4096 Jan 14 14:45 hats
-rw-r--r-- 1 minecraft minecraft   299884 Jan 14 14:45 Hats-1.12.2-7.0.2.jar
-rw-r--r-- 1 minecraft minecraft    33559 Jan 14 14:45 HatStand-1.12.2-7.0.1.jar
-rw-r--r-- 1 minecraft minecraft   453778 Jan 14 14:45 Hwyla-1.8.26-B41_1.12.2.jar
-rw-r--r-- 1 minecraft minecraft   550812 Jan 14 14:45 iChunUtil-1.12.2-7.1.4.jar
-rw-r--r-- 1 minecraft minecraft   285402 Apr 14  2018 IGW-Mod-1.12.2-1.4.4-15-universal.jar
-rw-r--r-- 1 minecraft minecraft   285799 Jan 14 14:45 InventoryTweaks-1.64+dev.145.jar
-rw-r--r-- 1 minecraft minecraft   465363 Jan 14 14:45 IronBackpacks-1.12.2-3.0.8-12.jar
-rw-r--r-- 1 minecraft minecraft   946221 Jan 14 14:45 ironchest-1.12.2-7.0.55.839.jar
-rw-r--r-- 1 minecraft minecraft   636384 Jan 14 14:45 jei_1.12.2-4.14.4.249.jar
-rw-r--r-- 1 minecraft minecraft  1831161 Jan 14 14:45 journeymap-1.12.2-5.5.3.jar
-rw-r--r-- 1 minecraft minecraft    19259 Jan 14 14:45 JustEnoughEnergistics-1.12.2-1.0.3.jar
-rw-r--r-- 1 minecraft minecraft   839004 Jan 14 14:45 Mantle-1.12-1.3.3.39.jar
-rw-r--r-- 1 minecraft minecraft   492317 Jan 14 14:45 mcjtylib-1.12-3.0.7.jar
-rw-r--r-- 1 minecraft minecraft 16020358 Jan 14 14:45 Mekanism-1.12.2-9.4.13.349.jar
-rw-r--r-- 1 minecraft minecraft   338984 Jan 14 14:45 MekanismGenerators-1.12.2-9.4.13.349.jar
-rw-r--r-- 1 minecraft minecraft   161142 Jan 14 14:45 MekanismTools-1.12.2-9.4.13.349.jar
drwxr-xr-x 4 minecraft minecraft     4096 Jan 14 14:45 memory_repo
-rw-r--r-- 1 minecraft minecraft  1268976 Jan 14 14:45 MineChem-1.12.2-2.0.12a.jar
-rw-r--r-- 1 minecraft minecraft    20837 Jan 14 14:45 Morpheus-1.12-3.3.2.jar
-rw-r--r-- 1 minecraft minecraft   799809 Jan 14 14:45 MrTJPCore-1.12.2-2.1.3.35-universal.jar
-rw-r--r-- 1 minecraft minecraft  2399088 Jan 14 14:45 mystcraft-1.12.2-0.13.7.02.jar
-rw-r--r-- 1 minecraft minecraft  1142333 Jan 14 14:45 natura-1.12.2-4.3.2.66.jar
-rw-r--r-- 1 minecraft minecraft   168253 Jan 14 14:45 notenoughwands-1.12-1.7.1.jar
-rw-r--r-- 1 minecraft minecraft    55227 Jan 14 14:45 ocdevices-snapshot_20190114.jar
-rw-r--r-- 1 minecraft minecraft  3217313 Jan 14 14:45 OpenBlocks-1.12.2-1.8.jar
-rw-r--r-- 1 minecraft minecraft 15543744 Jan 14 14:45 OpenComputers-MC1.12.2-1.7.3.146.jar
-rw-r--r-- 1 minecraft minecraft   422852 Jan 14 14:45 OpenGlasses-MC1.12.2-2.0.6.jar
-rw-r--r-- 1 minecraft minecraft  2639564 Jan 14 14:45 OpenModsLib-1.12.2-0.12.1.jar
-rw-r--r-- 1 minecraft minecraft   210911 Jan 14 14:45 OpenPrinter-1.12.2-0.1.0.2.jar
drwxr-xr-x 3 minecraft minecraft     4096 Jan 14 14:45 OpenSecurity
-rw-r--r-- 1 minecraft minecraft   398518 Jan 14 14:45 OpenSecurity-MC1.12.2-1.0-14.jar
-rw-r--r-- 1 minecraft minecraft  2444057 Jan 14 14:45 OptiFine_1.12.2_HD_U_E3.jar
-rw-r--r-- 1 minecraft minecraft   305888 Jan 14 14:45 p455w0rdslib-1.12.2-2.0.36.jar
-rw-r--r-- 1 minecraft minecraft  4738662 Jan 14 14:45 Pam's+HarvestCraft+1.12.2zb.jar
-rw-r--r-- 1 minecraft minecraft  1706607 Jan 14 14:45 PortalGun-1.12.2-7.0.2.jar
-rw-r--r-- 1 minecraft minecraft  1790588 Jan 14 14:45 ProjectE-1.12-PE1.3.2h.jar
-rw-r--r-- 1 minecraft minecraft  2032359 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-Base.jar
-rw-r--r-- 1 minecraft minecraft    62460 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-compat.jar
-rw-r--r-- 1 minecraft minecraft  1886213 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-fabrication.jar
-rw-r--r-- 1 minecraft minecraft  3921871 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-integration.jar
-rw-r--r-- 1 minecraft minecraft   724243 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-lighting.jar
-rw-r--r-- 1 minecraft minecraft  2586694 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-mechanical.jar
-rw-r--r-- 1 minecraft minecraft   501254 Jan 14 14:45 ProjectRed-1.12.2-4.9.1.92-world.jar
-rw-r--r-- 1 minecraft minecraft  2165670 Jan 21 15:29 Psi-r1.1-70.jar
-rw-r--r-- 1 minecraft minecraft  2054663 Jan 14 14:45 Quark-r1.5-141.jar
-rw-r--r-- 1 minecraft minecraft     7074 Jan 14 14:45 QuickLeafDecay-MC1.12.1-1.2.4.jar
-rw-r--r-- 1 minecraft minecraft  5493949 Jan 10 21:45 railcraft-12.0.0-beta-4.jar
-rw-r--r-- 1 minecraft minecraft   733793 Jan 11 19:09 RebornCore-1.12.2-3.13.1.402-universal.jar
-rw-r--r-- 1 minecraft minecraft    36278 Jan 14 14:45 RedstoneFlux-1.12-2.1.0.6-universal.jar
-rw-r--r-- 1 minecraft minecraft  2892808 Jan 14 14:45 rftools-1.12-7.59.jar
-rw-r--r-- 1 minecraft minecraft   590793 Jan 14 14:45 rftoolsctrl-1.12-1.9.2.jar
-rw-r--r-- 1 minecraft minecraft   607766 Jan 14 14:45 SolarFluxReborn_1.12.2-4.21r.jar
-rw-r--r-- 1 minecraft minecraft  2471468 Dec 30 16:37 StevesCarts-1.12.2-2.4.28.130.jar
-rw-r--r-- 1 minecraft minecraft   596220 Jan 14 14:45 StorageDrawers-1.12.2-5.3.8.jar
-rw-r--r-- 1 minecraft minecraft   402870 Jan 14 14:45 StorageDrawersExtras-1.12-3.1.0.jar
-rw-r--r-- 1 minecraft minecraft     9998 Jan 10  2018 StuffASockInIt-1.12.2-1.1.14.jar
-rw-r--r-- 1 minecraft minecraft  3945706 Jan 14 14:45 TConstruct-1.12.2-2.12.0.113.jar
-rw-r--r-- 1 minecraft minecraft 11360786 Jan 14 14:45 Thaumcraft-1.12.2-6.1.BETA26.jar
-rw-r--r-- 1 minecraft minecraft   597555 Jan 14 14:45 thaumicenergistics-2.1.0.jar
-rw-r--r-- 1 minecraft minecraft   761778 Jan 14 14:45 ThermalDynamics-1.12.2-2.5.3.16-universal.jar
-rw-r--r-- 1 minecraft minecraft  2411466 Jan 14 14:45 ThermalExpansion-1.12.2-5.5.2.39-universal.jar
-rw-r--r-- 1 minecraft minecraft  2304958 Jan 14 14:45 ThermalFoundation-1.12.2-2.6.1.22-universal.jar
-rw-r--r-- 1 minecraft minecraft    14676 Jan 14 14:45 tinkersoc-0.6.jar
-rw-r--r-- 1 minecraft minecraft    95850 Jan 14 14:45 TinkerToolLeveling-1.12.2-1.1.0.jar
-rw-r--r-- 1 minecraft minecraft  1129670 Jan 14 14:45 tinyprogressions-1.12.2-3.3.31-Release.jar
-rw-r--r-- 1 minecraft minecraft    16590 Jan 14 14:45 tmel-1.12.2-1.2.0.0.jar
-rw-r--r-- 1 minecraft minecraft   126020 Jan 14 14:45 Torched-1.12.2-7.0.0.jar
-rw-r--r-- 1 minecraft minecraft   446699 Jan 14 14:45 Translocators-1.12.2-2.5.1.77-universal.jar
-rw-r--r-- 1 minecraft minecraft  7296016 Jan 14 14:45 twilightforest-1.12.2-3.8.689-universal.jar
-rw-r--r-- 1 minecraft minecraft    96637 Jan 14 14:45 UnlimitedChiselWorks-0.2.0.jar
-rw-r--r-- 1 minecraft minecraft   725317 Jan 14 14:45 valkyrielib-1.12.2-2.0.19.1.jar
-rw-r--r-- 1 minecraft minecraft   128682 Jan 14 14:45 VeinMiner-1.12-0.38.2.647+b31535a.jar
-rw-r--r-- 1 minecraft minecraft   243080 Jan 14 14:45 WirelessCraftingTerminal-1.12.2-3.11.88.jar
-rw-r--r-- 1 minecraft minecraft   449444 Jan 14 14:45 Xtones-1.12-1.0.8-11.jar
-rw-r--r-- 1 minecraft minecraft   202790 Jan 14 14:45 zerocore-1.12-0.1.2.3.jar
```

**Comment by gudenau** [comment]
Turns out this is random.

Redid it and it did not die.

**Comment by liach** [comment]
i know there is a npe associated, but is there a stacktrace for the cme?

**Comment by gudenau** [comment]
The only related stack trace is the generic one from Minecraft. All the other ones in the log are handled and do not cause the game to crash, mostly related to compatibility with two other mods. Those would not be related to this one.

```
[15:42:20] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_181]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471) ~[?:1.8.0_181]
	at net.minecraft.world.World.func_147448_a(World.java:1946) ~[amu.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856) ~[axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraftforge.common.ForgeChunkManager.lambda$getPersistentChunksIterableFor$0(ForgeChunkManager.java:146) ~[forge-1.12.2-14.23.5.2807-universal.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_181]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[?:1.8.0_181]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[?:1.8.0_181]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169) ~[?:1.8.0_181]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[?:1.8.0_181]
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:1.8.0_181]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:436) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:534) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.common.ForgeChunkManager.getPersistentChunksIterableFor(ForgeChunkManager.java:146) ~[ForgeChunkManager.class:?]
	at net.minecraft.world.World.getPersistentChunkIterable(World.java:3930) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
```
