### ISSUE TITLE
Make server crashes when loading if forge version isn't 14.23.5.2779

### ISSUE THREAD

**Issue by AisakaPMD** [Railcraft/Railcraft#1860]
[...]
[14:46:12] [Server thread/INFO] [FML]: Searching /var/directory_serv/minecraft_207855/./mods for mods

[14:46:15] [Server thread/INFO] [FML]: Forge Mod Loader has identified 21 mods to load

[14:46:15] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang

[14:46:15] [Server thread/WARN] [FML]: Missing English translation for spongeapi: assets/spongeapi/lang/en_us.lang

[14:46:15] [Server thread/WARN] [FML]: Missing English translation for spongeforge: assets/spongeforge/lang/en_us.lang

[14:46:15] [Server thread/WARN] [FML]: Missing English translation for nucleus: assets/nucleus/lang/en_us.lang

[14:46:15] [Server thread/WARN] [FML]: Missing English translation for thutcore_compat: assets/thutcore_compat/lang/en_us.lang

[14:46:15] [Server thread/WARN] [FML]: Missing English translation for worldedit: assets/worldedit/lang/en_us.lang

[14:46:15] [Server thread/WARN] [Sponge]: The mod spongeforge was designed for forge 1.12.2-14.23.5.2825 but version 14.23.5.2768 is in use. It may not work properly.

[14:46:15] [Server thread/WARN] [Sponge]: The mod spongeforge was designed for forge 1.12.2-14.23.5.2825 but version 14.23.5.2768 is in use. It may not work properly.

[14:46:15] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod railcraft (Railcraft) requires [forge@[14.23.5.2779,)]

[14:46:15] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception

net.minecraftforge.fml.common.MissingModsException: Mod railcraft (Railcraft) requires [forge@[14.23.5.2779,)]

	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]

	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]

	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]

	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

[14:46:15] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /var/directory_serv/minecraft_207855/./crash-reports/crash-2019-07-15_14.46.15-server.txt

[14:46:15] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server

[14:46:15] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

[14:46:15] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.

[14:46:15] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server

[14:46:15] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

**Comment by CovertJaguar** [comment]
You MUST update Forge.
