### ISSUE TITLE
Server-Crash after trying to crafting (2x2) recipe

### ISSUE THREAD

**Issue by lightlike** [Railcraft/Railcraft#1950]
**Description of the Bug**
Server-Crash after trying to crafting an item.
Current testing showed some item on the way to the routing actuator. (Will edit when i know more)

Edit: seems to be any 2x2 crafting grid. If I place the items in the Refined Storage pattern on the bottom right there are no more crashes.

Edit 2: Converted all 2x2 Recipes to 3x3 but crashes still happen. Last one was trying to craft the Double-Headed Distant Signal, which does not even use any 2x2 crafting.

**Information**
Modpack: FTB Revelation (with some extra mods)
Railcraft-Version: 12.0.0-beta-5

**To Reproduce**
1. Place items in any 2x2 crafting grid
2. Remove item from result slot.

**Expected behavior**
Not crashing

**Logs & Environment**
- Exception (Refined Storage Example, similar when crafting manually):
```
java.lang.ArrayIndexOutOfBoundsException: 4
    at mods.railcraft.common.util.crafting.ShapedRailcraftRecipe.func_179532_b(ShapedRailcraftRecipe.java:68)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.getByproducts(CraftingPattern.java:232)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculateInternal(CraftingTask.java:538)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculateInternal(CraftingTask.java:403)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:265)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.request(CraftingManager.java:248)
    at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeInterface.update(NetworkNodeInterface.java:122)
    at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:24)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1450_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

 - Crash Report: 
https://pastebin.com/C35dwS4b

**Comment by CovertJaguar** [comment]
Closed by 1eb527b49655c157c915c54d5c1e6cfedba4e34a
