### ISSUE TITLE
[1.12.2] Server crash

### ISSUE THREAD

**Issue by MrLador** [Railcraft/Railcraft#1959]
Curseforge release 1.12.2
Something is causing a crash on the server. Everything is normal on the client.
```
[21:43:08] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:915) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
	at net.minecraft.tileentity.TileEntityHopper.func_145898_a(TileEntityHopper.java:453) ~[avw.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:378) ~[avw.class:?]
	at mods.railcraft.common.carts.EntityCartHopper.transferAndNeedsCooldown(EntityCartHopper.java:191) ~[EntityCartHopper.class:?]
	at mods.railcraft.common.carts.EntityCartHopper.TickCentral_TrueOnUpdateTick(EntityCartHopper.java:145) ~[EntityCartHopper.class:?]
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56) ~[TickHub.class:?]
	at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102) ~[LagGoggles-1.12.2-5.8-132.jar:?]
	at mods.railcraft.common.carts.EntityCartHopper.func_70071_h_(EntityCartHopper.java) ~[EntityCartHopper.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2294) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2248) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2022) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:857) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) ~[MinecraftServer.class:?]
	... 4 more
[21:43:08] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```

**Comment by CovertJaguar** [comment]
test
