### ISSUE TITLE
Crash while loading world (using last 1.12.2 version)

### ISSUE THREAD

**Issue by TheReveluvCat** [Railcraft/Railcraft#2004]
[latest.log](https://github.com/Railcraft/Railcraft/files/6020497/latest.log)
Hey, when I load any world I get this annoying crash, related to RC and Recipe Book. I posted the log, I believe, but the crash itself is:
[04:55:07] [Server thread/INFO] [FML]: Unloading dimension 2
[04:55:10] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: mods.railcraft.common.util.crafting.ShapedRailcraftRecipe@71ccc7d8 Name: railcraft:tool_crowbar_iron$1
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: mods.railcraft.common.util.crafting.ShapedRailcraftRecipe@71ccc7d8 Name: railcraft:tool_crowbar_iron$1
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53) ~[ql.class:?]
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35) ~[ql.class:?]
	at net.minecraft.client.gui.recipebook.RecipeList.func_194214_a(SourceFile:27) ~[bns.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.lambda$handleRecipeBook$2(NetHandlerPlayClient.java:1487) ~[brz.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient$$Lambda$2149/1620657951.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.client.network.NetHandlerPlayClient.func_191980_a(NetHandlerPlayClient.java:1485) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:39) ~[js.class:?]
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:12) ~[js.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 9 more
[04:55:17] [Client thread/INFO] [STDOUT]: [xaero.common.XaeroMinimapSession:cleanup:63]: Minimap session finalized.
[04:55:40] [Server thread/INFO] [FML]: Applying holder lookups
[latest.log](https://github.com/Railcraft/Railcraft/files/6020497/latest.log)

**Comment by CovertJaguar** [comment]
Are you using non-standard configs for Railcraft?
