### ISSUE TITLE
Redstone Flux Loader/Unloader - Game crash

### ISSUE THREAD

**Issue by Romz24** [Railcraft/Railcraft#2098]
**Description of the Bug**
When you try to open the interface of these machines, the game just freezes / crashes.

**To Reproduce**
1. Place Redstone Flux Loader or Unloader
2. Try to open their interface
3. Game freezes or crashes (always)

**Logs & Environment**
Crash log 1:
```
java.lang.NullPointerException
    at net.minecraft.inventory.Slot.getStack(Slot.java:60)
    at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:79)
    at mods.railcraft.common.gui.containers.RailcraftContainer.detectAndSendChanges(RailcraftContainer.java:92)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:324)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642)
    at net.minecraft.world.World.updateEntities(World.java:1737)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
```
Crash log 2:
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at net.minecraft.inventory.Slot.getStack(Slot.java:60)
    at net.minecraft.inventory.Container.getInventory(Container.java:63)
    at net.minecraft.inventory.Container.addListener(Container.java:52)
    at mods.railcraft.common.gui.containers.RailcraftContainer.addListener(RailcraftContainer.java:86)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at mods.railcraft.common.gui.GuiHandler.openGui(GuiHandler.java:34)
    at mods.railcraft.common.blocks.machine.manipulator.TileRFLoader.openGui(TileRFLoader.java:29)
    at mods.railcraft.common.blocks.ISmartTile.blockActivated(ISmartTile.java:55)
    at mods.railcraft.common.blocks.BlockEntityDelegate.lambda$onBlockActivated$0(BlockEntityDelegate.java:64)
    at mods.railcraft.common.blocks.BlockEntityDelegate$$Lambda$6174/356015401.apply(Unknown Source)
    at java.util.Optional.map(Optional.java:215)
    at mods.railcraft.common.blocks.BlockEntityDelegate.onBlockActivated(BlockEntityDelegate.java:64)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
```

**Additional context**
Railcraft version: **12.1.0-beta-8 - MC 1.12.2**

**Comment by xJon** [comment]
Resolved by https://github.com/3TUSK/RailwayDepotWorker/commit/8b410e244bce9d8e131d74d00006a6c40af19408.

**Comment by Romz24** [comment]
@xJon
Does your mod work with version 12.1.0-beta-8, or should we use the latest stable version 12.0.0?

**Comment by xJon** [comment]
@Romz24 Railway Depot Worker works with beta-8 (and is not my mod). Recommended to also use Universal Tweaks to disable the warning that prints to chat with Railcraft's beta versions.
