### ISSUE TITLE
[1.10-Alpha] Crash milking buckets

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#862]
```
java.lang.NullPointerException: Unexpected error
    at mods.railcraft.common.fluids.BucketHandler.fillCustomBucket(BucketHandler.java:47)
    at mods.railcraft.common.fluids.BucketHandler.onBucketFill(BucketHandler.java:37)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_127_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:335)
    at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

Tema's Zoology mod is installed, which could possibly make a difference.

**Comment by CovertJaguar** [comment]
More likely its simply because I commented out half the fluid code. =P
