### ISSUE TITLE
output for the railcraft alpha13 on 1.10.2 minecraft version forge

### ISSUE THREAD

**Issue by changemenemo** [Railcraft/Railcraft#867]
```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: javafx/collections/transformation/SortedList
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javafx/collections/transformation/SortedList
    at mods.railcraft.api.tracks.TrackRegistry.<clinit>(TrackRegistry.java:43)
    at mods.railcraft.common.blocks.tracks.kits.TrackKits.<clinit>(TrackKits.java:77)
    at mods.railcraft.common.core.RailcraftConfig.loadBlocks(RailcraftConfig.java:467)
    at mods.railcraft.common.core.RailcraftConfig.preInit(RailcraftConfig.java:150)
    at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:161)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: javafx.collections.transformation.SortedList
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
```

`-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 4.4.0-34-generic
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 300125016 bytes (286 MB) / 953155584 bytes (909 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xmx2048M -Xms256M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2046 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2046-universal.jar) 
    UCH Forge{12.18.1.2046} [Minecraft Forge] (forge-1.10.2-12.18.1.2046-universal.jar) 
    UCH CodeChickenCore{2.1.7.77} [CodeChicken Core] (minecraft.jar) 
    UCH ChickenChunks{2.1.2.34} [ChickenChunks] (ChickenChunks-1.10.2-2.1.2.34-universal.jar) 
    UCH IC2{2.6.30-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.30-ex110.jar) 
    UCH CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
    UCH Dynmap{2.3-3} [Dynmap] (Dynmap-2.3-forge-1.9.4.jar) 
    UCH EnderStorage{2.1.3.71} [EnderStorage] (EnderStorage-1.10.2-2.1.3.71-universal.jar) 
    UCH forestry{5.2.8.236} [Forestry] (forestry_1.10.2-5.2.8.236.jar) 
    UCE railcraft{10.0.0-alpha-13} [Railcraft] (Railcraft_1.10.2-10.0.0-alpha-13.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.30-ex110.jar)`

**Comment by changemenemo** [comment]
alpha 12 is working at startup without any errors by the way

**Comment by liach** [comment]
Bad use of library.

**Comment by changemenemo** [comment]
What do you mean?

Télécharger Outlook pour Androidhttps://aka.ms/ghei36

On Wed, Aug 17, 2016 at 1:47 AM +0200, "liach" <notifications@github.com<mailto:notifications@github.com>> wrote:

Bad use of library.

##

**Comment by CovertJaguar** [comment]
Fixed in alpha14
