### ISSUE TITLE
error railcraft 1.10 alpha 20

### ISSUE THREAD

**Issue by changemenemo** [Railcraft/Railcraft#884]
```
[03:39:30] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[03:39:30] [Server thread/ERROR] [FML/]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2076-universal.jar) 
    UCH Forge{12.18.1.2076} [Minecraft Forge] (forge-1.10.2-12.18.1.2076-universal.jar) 
    UCH CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
    UCH ChickenChunks{2.1.3.36} [ChickenChunks] (ChickenChunks-1.10.2-2.1.3.36-universal.jar) 
    UCH IC2{2.6.59-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.59-ex110.jar) 
    UCH CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
    UCH Dynmap{2.3-3} [Dynmap] (Dynmap-2.3-forge-1.9.4.jar) 
    UCH EnderStorage{2.1.3.73} [EnderStorage] (EnderStorage-1.10.2-2.1.3.73-universal.jar) 
    UCH forestry{5.2.9.242} [Forestry] (forestry_1.10.2-5.2.9.242.jar) 
    UCH ironchest{1.10.2-7.0.9.796} [Iron Chest] (ironchest-1.10.2-7.0.9.796.jar) 
    UCE railcraft{10.0.0-alpha-20} [Railcraft] (Railcraft_1.10.2-10.0.0-alpha-20.jar) 
    UCH Translocator{2.1.2.29} [Translocator] (Translocators-1.10.2-2.1.2.29-universal.jar) 
[03:39:30] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[03:39:30] [Server thread/ERROR] [FML/]: Caught exception from railcraft
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: mods.railcraft.common.blocks.tracks.outfitted.BlockTrackOutfitted.<init>()void/newInvokeSpecial
    at mods.railcraft.common.blocks.RailcraftBlocks.<clinit>(RailcraftBlocks.java:127) ~[RailcraftBlocks.class:?]
    at mods.railcraft.common.carts.RailcraftCarts$1.<init>(RailcraftCarts.java:66) ~[RailcraftCarts$1.class:?]
    at mods.railcraft.common.carts.RailcraftCarts.<clinit>(RailcraftCarts.java:64) ~[RailcraftCarts.class:?]
    at mods.railcraft.common.core.RailcraftConfig.loadCarts(RailcraftConfig.java:426) ~[RailcraftConfig.class:?]
    at mods.railcraft.common.core.RailcraftConfig.preInit(RailcraftConfig.java:154) ~[RailcraftConfig.class:?]
    at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:159) ~[Railcraft.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595) ~[forge-1.10.2-12.18.1.2076-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[forge-1.10.2-12.18.1.2076-universal.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[forge-1.10.2-12.18.1.2076-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalAccessError: no such constructor: mods.railcraft.common.blocks.tracks.outfitted.BlockTrackOutfitted.<init>()void/newInvokeSpecial
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_91]
    ... 37 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/IStateMapper
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_91]
    at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:977) ~[?:1.8.0_91]
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1002) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_91]
    ... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.statemap.IStateMapper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_91]
    at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:977) ~[?:1.8.0_91]
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1002) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_91]
    ... 37 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_91]
    at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:977) ~[?:1.8.0_91]
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1002) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) ~[?:1.8.0_91]
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_91]
    ... 37 more
```

**Comment by CovertJaguar** [comment]
Oh...a dedicated server error...yay... -.-

**Comment by liach** [comment]
@CovertJaguar It seems that more `@SideOnly` annotations may be necessary.

**Comment by CovertJaguar** [comment]
I need to make a release checklist or something. I always assume that the server will just work.
