### ISSUE TITLE
[1.10] Various firestone bugs

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#894]
- [x] Breaking a charged/charging firestone converts it between cracked & nominal
- [x] The charging firestone has a minor rendering error; it seems it is rendering twice & having Z-fighting. May be a fast/fancy issue.
- [x] Firestone ore appears to not spawn in the nether as judged by spending several minutes boating around with an IC2 OV scanner. (And the scanner does indeed detect cheat-placed ore.)
- [ ] When used, the firestone plays the 'ghast shot' sound. I prefer the original crackle sound.
- [x] Using a firestone on cobblestone causes the following crash:

```
java.lang.ClassCastException: net.minecraft.client.multiplayer.WorldClient cannot be cast to net.minecraft.world.WorldServer
    at mods.railcraft.common.items.firestone.ItemFirestoneRefined.func_180614_a(ItemFirestoneRefined.java:157)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:463)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

(Haven't tested it in furnaces.)

**Comment by CovertJaguar** [comment]
You are going to have to be more specific about what the old sound was. It currently uses the Fire Charge sound. Was is the flint and steel before?

**Comment by CovertJaguar** [comment]
Ok, it looks like the Nether doesn't spawn oreGen events so I'll need to do some refactoring to use DecorateBiomeEvent.Post.

**Comment by CovertJaguar** [comment]
Also added hitting an entity with a Firestone sets it on fire for 5 seconds.

**Comment by CovertJaguar** [comment]
Worldgen still broken
