### ISSUE TITLE
Broken Forestry Module

### ISSUE THREAD

**Issue by changemenemo** [Railcraft/Railcraft#899]
```
org.apache.logging.log4j.core.appender.AppenderLoggingException: An exception occurred processing Appender ServerGuiConsole
    at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:73)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:101)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
    at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1362)
    at mods.railcraft.common.util.misc.Game.log(Game.java:80)
    at mods.railcraft.common.util.misc.Game.log(Game.java:76)
    at mods.railcraft.common.util.misc.Game.logThrowable(Game.java:115)
    at mods.railcraft.common.util.misc.Game.logErrorAPI(Game.java:129)
    at mods.railcraft.common.plugins.forestry.ForestryPlugin$ForestryPluginInstalled.addCarpenterRecipe(ForestryPlugin.java:294)
    at mods.railcraft.common.modules.ModuleForestry$1.postInit(ModuleForestry.java:52)
    at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.postInit(RailcraftModulePayload.java:82)
    at mods.railcraft.common.modules.RailcraftModuleManager$Stage$4.passToModule(RailcraftModuleManager.java:278)
    at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:223)
    at mods.railcraft.common.modules.RailcraftModuleManager.postInit(RailcraftModuleManager.java:210)
    at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: can't parse argument number: concrete
    at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
    at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
    at java.text.MessageFormat.<init>(MessageFormat.java:362)
    at java.text.MessageFormat.format(MessageFormat.java:840)
    at org.apache.logging.log4j.message.MessageFormatMessage.formatMessage(MessageFormatMessage.java:89)
    at org.apache.logging.log4j.message.MessageFormatMessage.getFormattedMessage(MessageFormatMessage.java:61)
    at org.apache.logging.log4j.core.pattern.MessagePatternConverter.format(MessagePatternConverter.java:68)
    at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:36)
    at org.apache.logging.log4j.core.pattern.RegexReplacementConverter.format(RegexReplacementConverter.java:93)
    at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:36)
    at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:167)
    at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:52)
    at com.mojang.util.QueueLogAppender.append(QueueLogAppender.java:39)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
    ... 47 more
Caused by: java.lang.NumberFormatException: For input string: "concrete"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
    ... 60 more

```

**Comment by CovertJaguar** [comment]
Looks like the Forestry module is broken, you can disable that if you wish to continue using alpha23

**Comment by CovertJaguar** [comment]
Looks like stupid trivial error too, but I don't have access to my computer atm.
