### ISSUE TITLE
[1.10.2] Initialization error

### ISSUE THREAD

**Issue by ghost** [Railcraft/Railcraft#930]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.148-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.2.1.80-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/9/16 2:21 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at mods.railcraft.common.blocks.aesthetics.glass.BlockStrengthGlass.finalizeDefinition(BlockStrengthGlass.java:92)
    at mods.railcraft.common.blocks.RailcraftBlocks.finalizeDefinitions(RailcraftBlocks.java:155)
    at mods.railcraft.common.modules.ModuleCore$1.postInit(ModuleCore.java:340)
    at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.postInit(RailcraftModulePayload.java:82)
    at mods.railcraft.common.modules.RailcraftModuleManager$Stage$4.passToModule(RailcraftModuleManager.java:278)
    at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:223)
    at mods.railcraft.common.modules.RailcraftModuleManager.postInit(RailcraftModuleManager.java:210)
    at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at mods.railcraft.common.blocks.aesthetics.glass.BlockStrengthGlass.finalizeDefinition(BlockStrengthGlass.java:92)
    at mods.railcraft.common.blocks.RailcraftBlocks.finalizeDefinitions(RailcraftBlocks.java:155)
    at mods.railcraft.common.modules.ModuleCore$1.postInit(ModuleCore.java:340)
    at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.postInit(RailcraftModulePayload.java:82)
    at mods.railcraft.common.modules.RailcraftModuleManager$Stage$4.passToModule(RailcraftModuleManager.java:278)
    at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:223)
    at mods.railcraft.common.modules.RailcraftModuleManager.postInit(RailcraftModuleManager.java:210)
    at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 863362776 bytes (823 MB) / 2278031360 bytes (2172 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.2.2097 Optifine OptiFine_1.10.2_HD_U_C3 39 mods loaded, 39 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2097-universal.jar) 
    UCHIJ   Forge{12.18.2.2097} [Minecraft Forge](forge-1.10.2-12.18.2.2097-universal.jar) 
    UCHIJ   CodeChickenCore{2.2.1.80} [CodeChicken Core](minecraft.jar) 
    UCHIJ   NotEnoughItems{2.1.1.148} [Not Enough Items](NotEnoughItems-1.10.2-2.1.1.148-universal.jar) 
    UCHIJ   backpack{3.0.1} [Backpack](backpack-3.0.1-1.10.2.jar) 
    UCHIJ   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJ   BaublesHud{3.0.0} [Baubles-Hud](BaublesHud-1.9.4-3.0.0.jar) 
    UCHIJ   bdlib{1.12.2.8} [BD Lib](bdlib-1.12.2.8-mc1.10.2.jar) 
    UCHIJ   guideapi{@VERSION@} [Guide-API](Guide-API-1.10.2-2.0.2-45.jar) 
    UCHIJ   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCHIJ   immersiveengineering{0.10-41} [Immersive Engineering](ImmersiveEngineering-0.10-41.jar) 
    UCHIJ   JEI{3.12.6.304} [Just Enough Items](jei_1.10.2-3.12.6.304.jar) 
    UCHIJ   BloodMagic{1.9.4-2.1.0-65} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.1.0-65 %281%29.jar) 
    UCHIJ   Botania{r1.9-327} [Botania](Botania r1.9-327.jar) 
    UCHIJ   brandonscore{2.1.0} [Brandon's Core](BrandonsCore-1.10.2-2.1.0.44-universal.jar) 
    UCHIJ   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJ   ChickenChunks{2.1.4.38} [ChickenChunks](ChickenChunks-1.10.2-2.1.4.38-universal.jar) 
    UCHIJ   chisel{MC1.9.4-0.0.6.42} [Chisel](Chisel-MC1.9.4-0.0.6.42.jar) 
    UCHIJ   craftingtweaks{6.1.14} [Crafting Tweaks](CraftingTweaks_1.10.2-6.1.14.jar) 
    UCHIJ   CustomMainMenu{2.0.2} [Custom Main Menu](CustomMainMenu-MC1.10.2-2.0.2.jar) 
    UCHIJ   draconicevolution{2.0.0} [Draconic Evolution](Draconic-Evolution-1.10.2-2.0.0.100-universal.jar) 
    UCHIJ   endercore{1.10.2-0.4.1.55-beta} [EnderCore](EnderCore-1.10.2-0.4.1.55-beta.jar) 
    UCHIJ   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJ   EnderIO{1.10.2-3.0.1.110_beta} [Ender IO](EnderIO-1.10.2-3.0.1.110_beta.jar) 
    UCHIJ   EnderStorage{2.1.4.77} [EnderStorage](EnderStorage-1.10.2-2.1.4.77-universal.jar) 
    UCHIJ   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.10.2-1.2.2.jar) 
    UCHIJ   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJ   LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UCHIJ   harvestcraft{1.9.4-1.10.2e} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2e.jar) 
    UCHIE   railcraft{10.0.0-beta-2} [Railcraft](Railcraft_1.10.2-10.0.0-beta-2.jar) 
    UCHIJ   realdrops{1.0.7} [Realistic Item Drops](RealisticItemDrops-1.0.7.jar) 
    UCHIJ   ResourceLoader{1.5.1} [Resource Loader](ResourceLoader-MC1.9.4-1.5.1.jar) 
    UCHIJ   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJ   simplyjetpacks{2.0.2.9} [Simply Jetpacks 2](SimplyJetpacks2-1.10.2-2.0.2.9.jar) 
    UCHIJ   StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJ   Translocator{2.1.2.30} [Translocator](Translocators-1.10.2-2.1.2.30-universal.jar) 
    UCHIJ   WailaHarvestability{1.1.8} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.8.jar) 
    UCHIJ   mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.148-universal.jar)
  codechicken.nei.asm.NEITransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.2.1.80-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
CCCDeobfPlugin (unknown)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)

CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 20.19.0.32837' Renderer: 'AMD Radeon R7 200 Series'
    CodeChickenCore: ignoreInvalidMCVersion state: false
    List of loaded APIs: 
        \* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
        \* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.1.0-65 (1).jar
        \* BotaniaAPI (82) from Botania r1.9-327.jar
        \* ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.6.42.jar
        \* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.6.42.jar
        \* CoFHAPI (1.8.9R1.2.0B1) from ImmersiveEngineering-0.10-41.jar
        \* CoFHAPI|energy (1.8.9R1.2.0B1) from BrandonsCore-1.10.2-2.1.0.44-universal.jar
        \* CraftingTweaks|API (4.1) from CraftingTweaks_1.10.2-6.1.14.jar
        \* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.0.100-universal.jar
        \* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
        \* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
        \* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
        \* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
        \* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
        \* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-41.jar
        \* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-41.jar
        \* JustEnoughItemsAPI (4.9.0) from jei_1.10.2-3.12.6.304.jar
        \* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.0-beta-2.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
        \* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
    EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  \* Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Detailed RF API diagnostics:
                  \* RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/EnergyStorage.class
                  \* RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  \* RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  \* RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  \* RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  \* RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  \* RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  \* RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/TileEnergyHandler.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/André/Desktop/MultiMC/instances/FluxModpack/minecraft/mods/BrandonsCore-1.10.2-2.1.0.44-universal.jar!/cofh/api/energy/TileEnergyHandler.class

```
Launched Version: MultiMC5
LWJGL: 2.9.1
OpenGL: AMD Radeon R7 200 Series GL version 4.5.13447 Compatibility Profile Context 20.19.0.32837, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Unity-1.3.1.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C3
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13447 Compatibility Profile Context 20.19.0.32837
OpenGlRenderer: AMD Radeon R7 200 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4
```

**Comment by CovertJaguar** [comment]
Some information about what you did differently to cause this would be helpful.

**Comment by CovertJaguar** [comment]
Try without any core mods.

**Comment by ghost** [comment]
When the mod start to load, instantly crashs and MC closes.

**Comment by Ristellise** [comment]
try without multimc

**Comment by AEnterprise** [comment]
can you try updating forge to the latest version? there was a problem with proxy injections and iirc RC has multiple proxies
https://github.com/MinecraftForge/MinecraftForge/pull/3300

**Comment by ghost** [comment]
I update to Forge 2098 and works fine, you can close
