### ISSUE TITLE
Crashing on 1.10.2

### ISSUE THREAD

**Issue by Jax2** [Railcraft/Railcraft#966]
Hi all, when I try to use this mod with 1.10.2, it crashes every time. Crash log is as follows: 

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.2.8.5.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/25/16 10:29 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at mods.railcraft.common.blocks.aesthetics.glass.BlockStrengthGlass.finalizeDefinition(BlockStrengthGlass.java:92)
    at mods.railcraft.common.blocks.RailcraftBlocks.finalizeDefinitions(RailcraftBlocks.java:155)
    at mods.railcraft.common.modules.ModuleCore$1.postInit(ModuleCore.java:340)
    at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.postInit(RailcraftModulePayload.java:82)
    at mods.railcraft.common.modules.RailcraftModuleManager$Stage$4.passToModule(RailcraftModuleManager.java:278)
    at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:223)
    at mods.railcraft.common.modules.RailcraftModuleManager.postInit(RailcraftModuleManager.java:210)
    at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at mods.railcraft.common.blocks.aesthetics.glass.BlockStrengthGlass.finalizeDefinition(BlockStrengthGlass.java:92)
    at mods.railcraft.common.blocks.RailcraftBlocks.finalizeDefinitions(RailcraftBlocks.java:155)
    at mods.railcraft.common.modules.ModuleCore$1.postInit(ModuleCore.java:340)
    at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.postInit(RailcraftModulePayload.java:82)
    at mods.railcraft.common.modules.RailcraftModuleManager$Stage$4.passToModule(RailcraftModuleManager.java:278)
    at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:223)
    at mods.railcraft.common.modules.RailcraftModuleManager.postInit(RailcraftModuleManager.java:210)
    at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 290305400 bytes (276 MB) / 662892544 bytes (632 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.2.2097 10 mods loaded, 10 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2097.jar) 
    UCHIJ   Forge{12.18.2.2097} [Minecraft Forge](forge-1.10.2-12.18.2.2097.jar) 
    UCHIJ   ivtoolkit{1.2.8.5} [IvToolkit](minecraft.jar) 
    UCHIJ   JEI{3.12.7.312} [Just Enough Items](jei_1.10.2-3.12.7.312.jar) 
    UCHIJ   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIE   railcraft{10.0.0-beta-2} [Railcraft](Railcraft_1.10.2-10.0.0-beta-2.jar) 
    UCHIJ   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJ   icse{1.1.0.0} [I Can See Everything](Wawla-1.10.2-2.3.0.206.jar) 
    UCHIJ   wawla{2.3.0.202} [What Are We Looking At](Wawla-1.10.2-2.3.0.206.jar) 
    Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.2.8.5.jar)

```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.50' Renderer: 'GeForce GTX 760/PCIe/SSE2'
Launched Version: 1.10.2-forge1.10.2-12.18.2.2097
LWJGL: 2.9.4
OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.50, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x AMD FX(tm)-8300 Eight-Core Processor `
```

**Comment by CovertJaguar** [comment]
Update Forge.

**Comment by CovertJaguar** [comment]
Duplicate of #930
